<?php

namespace AppBundle\Repository;

/**
 * musicStyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class musicStyleRepository extends \Doctrine\ORM\EntityRepository
{
}
